# Generated by Django 5.2.4 on 2025-08-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_sell_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.vendor'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='base.product'),
        ),
    ]
